version: '3.9'
services:
  poi-service:
    build: .
    container_name: poi-service
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - private-network
    volumes:
      - .:/app

  poi-db:
    image: postgres:latest
    container_name: poi-server
    volumes:
      - db-storage:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: poi-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
    ports:
      - 3377:5432
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
volumes:
  db-storage:
    driver: local
